# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: https://github.com/ovaldi
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "/favicon.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: ovaldi
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  我的博客园: http://raoh.cnblogs.com/
  我的GitHub: https://github.com/ovaldi

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 码农，棋迷，宅男，喜欢许巍和朴树的歌，最喜欢的诗人是海子，最想去的地方是西藏